version: '3.0'

services:
  web:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: web
    tty: true
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./apache2/sites-available/:/etc/apache2/sites-enabled/
      # apps
      - ${APP_SRC}:/var/www/${APP_NAME}/
    networks:
      - web-network

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    ports:
      - '5432:5432'
    tty: true
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: //var/lib/postgresql/data/pgdate
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdate
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  dbdata:
    driver: local